apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: l7puxxajv-go-gitops
  description: This is GitOps manifest for l7puxxajv-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=l7puxxajv-go
    backstage.io/kubernetes-id: l7puxxajv-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: l7puxxajv-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:l7puxxajv-go
